/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package capapresentacion;
import javax.swing.JOptionPane;
/**
 *
 * @author user
 */
public class frmEgresante extends javax.swing.JFrame {

    /**
     * Creates new form frmEgresante
     */
    public frmEgresante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombres = new javax.swing.JTextField();
        cboLugarNac = new javax.swing.JComboBox<>();
        txtCodigo = new javax.swing.JTextField();
        txtDni = new javax.swing.JTextField();
        lblIngresante = new javax.swing.JLabel();
        txtCreditosAcum = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtFechaNac = new javax.swing.JTextField();
        txtPracticas = new javax.swing.JTextField();
        btnHistorialNot = new javax.swing.JButton();
        btnEscribir = new javax.swing.JButton();
        btnLeer = new javax.swing.JButton();
        btnMatricularse = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(245, 237, 204));

        txtNombres.setBackground(new java.awt.Color(244, 233, 126));
        txtNombres.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtNombres.setText("Nombres");

        cboLugarNac.setBackground(new java.awt.Color(244, 233, 126));
        cboLugarNac.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cboLugarNac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una región...", "Amazonas", "Ancash", "Apurímac", "Arequipa", "Ayacucho", "Cajamarca", "Callao", "Cusco", "Huancavelica", "Huanuco", "Ica", "Junín", "La libertad", "Lambayeque", "Lima", "Loreto", "Madre de Dios", "Moquegua", "Pasco", "Piura", "Puno", "San Martín", "Tacna", "Tumbes", "Ucayali" }));
        cboLugarNac.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtCodigo.setBackground(new java.awt.Color(244, 233, 126));
        txtCodigo.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtCodigo.setText("Código");

        txtDni.setBackground(new java.awt.Color(244, 233, 126));
        txtDni.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtDni.setText("DNI");

        lblIngresante.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        lblIngresante.setForeground(new java.awt.Color(242, 164, 32));
        lblIngresante.setText("Matrícula Alumno Egresante");

        txtCreditosAcum.setBackground(new java.awt.Color(244, 233, 126));
        txtCreditosAcum.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtCreditosAcum.setText("Créditos Acumulados");
        txtCreditosAcum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCreditosAcumActionPerformed(evt);
            }
        });

        txtApellidos.setBackground(new java.awt.Color(244, 233, 126));
        txtApellidos.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtApellidos.setText("Apellidos");

        txtFechaNac.setBackground(new java.awt.Color(244, 233, 126));
        txtFechaNac.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtFechaNac.setText("Día/Mes/Año");
        txtFechaNac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaNacActionPerformed(evt);
            }
        });

        txtPracticas.setBackground(new java.awt.Color(244, 233, 126));
        txtPracticas.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtPracticas.setText("Prácticas");
        txtPracticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPracticasActionPerformed(evt);
            }
        });

        btnHistorialNot.setBackground(new java.awt.Color(106, 202, 236));
        btnHistorialNot.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnHistorialNot.setText("Historial de Notas");
        btnHistorialNot.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        btnHistorialNot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialNotActionPerformed(evt);
            }
        });

        btnEscribir.setBackground(new java.awt.Color(41, 212, 212));
        btnEscribir.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnEscribir.setText("Escribir");
        btnEscribir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscribirActionPerformed(evt);
            }
        });

        btnLeer.setBackground(new java.awt.Color(185, 232, 207));
        btnLeer.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnLeer.setText("Leer");
        btnLeer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLeer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeerActionPerformed(evt);
            }
        });

        btnMatricularse.setBackground(new java.awt.Color(92, 202, 186));
        btnMatricularse.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnMatricularse.setForeground(new java.awt.Color(0, 153, 153));
        btnMatricularse.setText("Matrícularse");
        btnMatricularse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMatricularse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatricularseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblIngresante)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cboLugarNac, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtFechaNac)
                    .addComponent(txtNombres)
                    .addComponent(txtApellidos)
                    .addComponent(txtDni)
                    .addComponent(txtCodigo))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(txtCreditosAcum, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnHistorialNot, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnEscribir)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnLeer, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(12, 12, 12))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnMatricularse)
                                .addGap(45, 45, 45))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtPracticas, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIngresante)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCreditosAcum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPracticas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboLugarNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btnHistorialNot)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEscribir)
                            .addComponent(btnLeer))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMatricularse)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    static capanegocio.Egresante egresante = new capanegocio.Egresante();
    private void txtCreditosAcumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCreditosAcumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCreditosAcumActionPerformed

    private void txtFechaNacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaNacActionPerformed

    }//GEN-LAST:event_txtFechaNacActionPerformed

    private void txtPracticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPracticasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPracticasActionPerformed

    private void btnHistorialNotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialNotActionPerformed
        JOptionPane.showMessageDialog(null, "En Mantenimiento");
    }//GEN-LAST:event_btnHistorialNotActionPerformed

    private void btnEscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscribirActionPerformed
        String codigo = txtCodigo.getText();
        String dni = txtDni.getText();
        String apellidos = txtApellidos.getText();
        String nombres = txtNombres.getText();
        String fechaNac = txtFechaNac.getText();
        String creditosAcum = txtCreditosAcum.getText();
        String practicas = txtPracticas.getText();
        //Lugar de Nacimiento
        String lugarNac = cboLugarNac.getSelectedItem().toString();

        //Declarar un objeto alumno egresante
        egresante.setCodigo(codigo);
        egresante.setDni(dni);
        egresante.setApellidos(apellidos);
        egresante.setNombres(nombres);
        egresante.setFechaNac(fechaNac);
        egresante.setLugarNac(lugarNac);
        egresante.setCreditosAcum(creditosAcum);
        egresante.setPracticas(practicas);

        //enviar mensaje de confirmación
        JOptionPane.showMessageDialog(null, "Los datos del alumno regular fueron registrados correctamente");
    }//GEN-LAST:event_btnEscribirActionPerformed

    private void btnLeerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeerActionPerformed
        //traer los atributos del objeto ingresante
        JOptionPane.showMessageDialog(null, "Datos del Alumno Egresante\n" +
            "\nCodigo: "+egresante.getCodigo()+"\nDNI: "+egresante.getDni()+
            "\nApellidos: "+egresante.getApellidos()+"\nNombres: "+
            egresante.getNombres()+"\nFecha de Nacimiento: "+egresante.getFechaNac()+
            "\nLugar de Nacimiento: "+egresante.getLugarNac()+
            "\nModalidad de Ingreso: "+egresante.getCreditosAcum()+"\nPrácticas: "+egresante.getPracticas());
    }//GEN-LAST:event_btnLeerActionPerformed

    private void btnMatricularseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatricularseActionPerformed
        //dirigir a Matricula
        capapresentacion.frmFacultad frm = new capapresentacion.frmFacultad();
        //mostrar el formulario
        frm.show();
    }//GEN-LAST:event_btnMatricularseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEgresante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEgresante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEgresante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEgresante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEgresante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEscribir;
    private javax.swing.JButton btnHistorialNot;
    private javax.swing.JButton btnLeer;
    private javax.swing.JButton btnMatricularse;
    private javax.swing.JComboBox<String> cboLugarNac;
    private javax.swing.JLabel lblIngresante;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCreditosAcum;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtFechaNac;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtPracticas;
    // End of variables declaration//GEN-END:variables
}
