/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package capapresentacion;

/**
 *
 * @author user
 */
public class frmEscuelaProfesional extends javax.swing.JFrame {

    /**
     * Creates new form frmEscuelaProfesional
     */
    public frmEscuelaProfesional() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnArquitectura = new javax.swing.JButton();
        btnIngenieriaAmb = new javax.swing.JButton();
        btnIngenieriaCiv = new javax.swing.JButton();
        btnIngenieriaSis = new javax.swing.JButton();
        btnIngenieriaInd = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnArquitectura.setBackground(new java.awt.Color(194, 237, 244));
        btnArquitectura.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnArquitectura.setForeground(new java.awt.Color(153, 153, 0));
        btnArquitectura.setText("Arquitectura");
        btnArquitectura.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnArquitectura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArquitecturaActionPerformed(evt);
            }
        });

        btnIngenieriaAmb.setBackground(new java.awt.Color(194, 237, 244));
        btnIngenieriaAmb.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnIngenieriaAmb.setForeground(new java.awt.Color(0, 51, 255));
        btnIngenieriaAmb.setText("Ingeniería Ambiental");
        btnIngenieriaAmb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngenieriaAmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngenieriaAmbActionPerformed(evt);
            }
        });

        btnIngenieriaCiv.setBackground(new java.awt.Color(194, 237, 244));
        btnIngenieriaCiv.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnIngenieriaCiv.setForeground(new java.awt.Color(0, 153, 153));
        btnIngenieriaCiv.setText("Ingeniería Civil");
        btnIngenieriaCiv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngenieriaCiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngenieriaCivActionPerformed(evt);
            }
        });

        btnIngenieriaSis.setBackground(new java.awt.Color(194, 237, 244));
        btnIngenieriaSis.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnIngenieriaSis.setForeground(new java.awt.Color(51, 153, 255));
        btnIngenieriaSis.setText("Ingeniería de Sistemas");
        btnIngenieriaSis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngenieriaSis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngenieriaSisActionPerformed(evt);
            }
        });

        btnIngenieriaInd.setBackground(new java.awt.Color(194, 237, 244));
        btnIngenieriaInd.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnIngenieriaInd.setForeground(new java.awt.Color(204, 0, 0));
        btnIngenieriaInd.setText("Ingeniería Industrial");
        btnIngenieriaInd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngenieriaInd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngenieriaIndActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setText("Ingeniería y Arquitectura");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnIngenieriaCiv, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(109, 109, 109))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnIngenieriaSis, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(btnIngenieriaInd, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnArquitectura, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(btnIngenieriaAmb, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel1)))
                .addContainerGap(258, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnArquitectura, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIngenieriaAmb, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnIngenieriaCiv, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngenieriaSis, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIngenieriaInd, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnArquitecturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArquitecturaActionPerformed
        //llamar al formulario Plan de Estudio
        capapresentacion.frmPlanEstudio frm = new capapresentacion.frmPlanEstudio();
        //Mostrar el formulario
        frm.show();
    }//GEN-LAST:event_btnArquitecturaActionPerformed

    private void btnIngenieriaAmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngenieriaAmbActionPerformed
        //llamar al formulario Plan de Estudio
        capapresentacion.frmPlanEstudio frm = new capapresentacion.frmPlanEstudio();
        //Mostrar el formulario
        frm.show();
    }//GEN-LAST:event_btnIngenieriaAmbActionPerformed

    private void btnIngenieriaCivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngenieriaCivActionPerformed
        //llamar al formulario Plan de Estudio
        capapresentacion.frmPlanEstudio frm = new capapresentacion.frmPlanEstudio();
        //Mostrar el formulario
        frm.show();
    }//GEN-LAST:event_btnIngenieriaCivActionPerformed

    private void btnIngenieriaSisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngenieriaSisActionPerformed
        //llamar al formulario Plan de Estudio
        capapresentacion.frmPlanEstudio frm = new capapresentacion.frmPlanEstudio();
        //Mostrar el formulario
        frm.show();
    }//GEN-LAST:event_btnIngenieriaSisActionPerformed

    private void btnIngenieriaIndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngenieriaIndActionPerformed
        //llamar al formulario Plan de Estudio
        capapresentacion.frmPlanEstudio frm = new capapresentacion.frmPlanEstudio();
        //Mostrar el formulario
        frm.show();
    }//GEN-LAST:event_btnIngenieriaIndActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEscuelaProfesional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEscuelaProfesional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEscuelaProfesional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEscuelaProfesional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEscuelaProfesional().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArquitectura;
    private javax.swing.JButton btnIngenieriaAmb;
    private javax.swing.JButton btnIngenieriaCiv;
    private javax.swing.JButton btnIngenieriaInd;
    private javax.swing.JButton btnIngenieriaSis;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
