/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package capapresentacion;

import java.util.HashSet;
import java.util.Set;
import javax.swing.DefaultButtonModel;
import javax.swing.plaf.OptionPaneUI;
import javax.xml.ws.handler.MessageContext;
import javax.swing.JOptionPane;
/**
 *
 * @author user
 */
public class frmIngresante extends javax.swing.JFrame {

    /**
     * Creates new form frmIngresante
     */
    public frmIngresante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtApellidos = new javax.swing.JTextField();
        btnMatricularse = new javax.swing.JButton();
        txtNombres = new javax.swing.JTextField();
        btnEscribir = new javax.swing.JButton();
        txtFechaNac = new javax.swing.JTextField();
        btnLeer = new javax.swing.JButton();
        cboLugarNac = new javax.swing.JComboBox<>();
        txtCodigo = new javax.swing.JTextField();
        txtDni = new javax.swing.JTextField();
        lblIngresante = new javax.swing.JLabel();
        txtNotaIngreso = new javax.swing.JTextField();
        cboModalidadIngr = new javax.swing.JComboBox<>();
        txtOrientacion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(246, 234, 234));

        txtApellidos.setBackground(new java.awt.Color(230, 218, 218));
        txtApellidos.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtApellidos.setText("Apellidos");

        btnMatricularse.setBackground(new java.awt.Color(92, 202, 186));
        btnMatricularse.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnMatricularse.setForeground(new java.awt.Color(0, 153, 153));
        btnMatricularse.setText("Matrícularse");
        btnMatricularse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMatricularse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatricularseActionPerformed(evt);
            }
        });

        txtNombres.setBackground(new java.awt.Color(230, 218, 218));
        txtNombres.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtNombres.setText("Nombres");

        btnEscribir.setBackground(new java.awt.Color(41, 212, 212));
        btnEscribir.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnEscribir.setText("Escribir");
        btnEscribir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscribirActionPerformed(evt);
            }
        });

        txtFechaNac.setBackground(new java.awt.Color(230, 218, 218));
        txtFechaNac.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtFechaNac.setText("Día/Mes/Año");
        txtFechaNac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaNacActionPerformed(evt);
            }
        });

        btnLeer.setBackground(new java.awt.Color(185, 232, 207));
        btnLeer.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnLeer.setText("Leer");
        btnLeer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLeer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeerActionPerformed(evt);
            }
        });

        cboLugarNac.setBackground(new java.awt.Color(230, 218, 218));
        cboLugarNac.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cboLugarNac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una región...", "Amazonas", "Ancash", "Apurímac", "Arequipa", "Ayacucho", "Cajamarca", "Callao", "Cusco", "Huancavelica", "Huanuco", "Ica", "Junín", "La libertad", "Lambayeque", "Lima", "Loreto", "Madre de Dios", "Moquegua", "Pasco", "Piura", "Puno", "San Martín", "Tacna", "Tumbes", "Ucayali" }));
        cboLugarNac.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtCodigo.setBackground(new java.awt.Color(230, 218, 218));
        txtCodigo.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtCodigo.setText("Código");

        txtDni.setBackground(new java.awt.Color(230, 218, 218));
        txtDni.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtDni.setText("DNI");

        lblIngresante.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        lblIngresante.setForeground(new java.awt.Color(255, 51, 51));
        lblIngresante.setText("Matrícula Alumno Ingresante");

        txtNotaIngreso.setBackground(new java.awt.Color(230, 218, 218));
        txtNotaIngreso.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtNotaIngreso.setText("Nota de Ingreso");

        cboModalidadIngr.setBackground(new java.awt.Color(230, 218, 218));
        cboModalidadIngr.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cboModalidadIngr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "seleccione la modalidad...", "Ordinario", "Exonerado", "5to de Secundaria", "Preferente", "Centro Pre Universitario" }));
        cboModalidadIngr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtOrientacion.setBackground(new java.awt.Color(230, 218, 218));
        txtOrientacion.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtOrientacion.setText("Orientación");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lblIngresante))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cboLugarNac, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtFechaNac)
                            .addComponent(txtNombres)
                            .addComponent(txtApellidos)
                            .addComponent(txtDni)
                            .addComponent(txtCodigo))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cboModalidadIngr, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtNotaIngreso)
                                    .addComponent(txtOrientacion)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEscribir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnLeer, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(btnMatricularse)))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEscribir)
                            .addComponent(btnLeer))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMatricularse)
                        .addGap(1, 1, 1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblIngresante)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboModalidadIngr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNotaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOrientacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboLugarNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(115, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Declarar objeto

    static capanegocio.Ingresante ingresante = new capanegocio.Ingresante();
    private void btnEscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscribirActionPerformed
        String codigo = txtCodigo.getText();
        String dni = txtDni.getText();
        String apellidos = txtApellidos.getText();
        String nombres = txtNombres.getText();
        String fechaNac = txtFechaNac.getText();
        String orientacion = txtOrientacion.getText();
        //Lugar de Nacimiento
        String lugarNac = cboLugarNac.getSelectedItem().toString();
        
        //Modalidad Ingresante
        String modalidadIngr = cboModalidadIngr.getSelectedItem().toString();
        
        //Declarar un objeto alumno
        ingresante.setCodigo(codigo);
        ingresante.setDni(dni);
        ingresante.setApellidos(apellidos);
        ingresante.setNombres(nombres);
        ingresante.setFechaNac(fechaNac);
        ingresante.setOrientacion(orientacion);
        ingresante.setLugarNac(lugarNac);
        ingresante.setModalidadIngr(modalidadIngr);

        //enviar mensaje de confirmación
        JOptionPane.showMessageDialog(null, "Los datos del alumno ingresante fueron registrados correctamente");
    }//GEN-LAST:event_btnEscribirActionPerformed

    private void btnLeerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeerActionPerformed
        //traer los atributos del objeto ingresante
         JOptionPane.showMessageDialog(null, "Datos del Alumno Ingresante\n" + 
                                       "\nCodigo: "+ingresante.getCodigo()+"\nDNI: "+ingresante.getDni()+
                                       "\nApellidos: "+ingresante.getApellidos()+"\nNombres: "+
                                       ingresante.getNombres()+"\nFecha de Nacimiento: "+ingresante.getFechaNac()+
                                       "\nOrientacion: "+ingresante.getOrientacion()+
                                       "\nLugar de Nacimiento: "+ingresante.getLugarNac()+
                                       "\nModalidad de Ingreso: "+ingresante.getModalidadIngr());
    }//GEN-LAST:event_btnLeerActionPerformed

    private void btnMatricularseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatricularseActionPerformed
        //dirigir a Matricula
        capapresentacion.frmFacultad frm = new capapresentacion.frmFacultad();
        //mostrar el formulario
        frm.show();
    }//GEN-LAST:event_btnMatricularseActionPerformed

    private void txtFechaNacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaNacActionPerformed
       
    }//GEN-LAST:event_txtFechaNacActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmIngresante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmIngresante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmIngresante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmIngresante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmIngresante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEscribir;
    private javax.swing.JButton btnLeer;
    private javax.swing.JButton btnMatricularse;
    private javax.swing.JComboBox<String> cboLugarNac;
    private javax.swing.JComboBox<String> cboModalidadIngr;
    private javax.swing.JLabel lblIngresante;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtFechaNac;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtNotaIngreso;
    private javax.swing.JTextField txtOrientacion;
    // End of variables declaration//GEN-END:variables
}
