/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package capapresentacion;
import javax.swing.JOptionPane;
public class frmPlanEstudio extends javax.swing.JFrame {

    /**
     * Creates new form frmPlanEstudio
     */
    public frmPlanEstudio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCiclo = new javax.swing.JTextField();
        txtCreditos = new javax.swing.JTextField();
        txtAño = new javax.swing.JTextField();
        btnEscribir = new javax.swing.JButton();
        btnPlanEstudios = new javax.swing.JButton();
        btnCatalogoAsig = new javax.swing.JButton();
        btnBoleta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("Plan de Estudio");

        txtCiclo.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtCiclo.setText("Ciclo");

        txtCreditos.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtCreditos.setText("Creditos");

        txtAño.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtAño.setText("Año");

        btnEscribir.setBackground(new java.awt.Color(126, 218, 197));
        btnEscribir.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnEscribir.setText("Escribir");
        btnEscribir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscribirActionPerformed(evt);
            }
        });

        btnPlanEstudios.setBackground(new java.awt.Color(204, 255, 255));
        btnPlanEstudios.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnPlanEstudios.setForeground(new java.awt.Color(0, 51, 255));
        btnPlanEstudios.setText("Plan de Estudios");
        btnPlanEstudios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPlanEstudios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlanEstudiosActionPerformed(evt);
            }
        });

        btnCatalogoAsig.setFont(new java.awt.Font("Tahoma", 2, 15)); // NOI18N
        btnCatalogoAsig.setForeground(new java.awt.Color(255, 51, 51));
        btnCatalogoAsig.setText("Catalogo de Asignaturas");
        btnCatalogoAsig.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        btnCatalogoAsig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCatalogoAsigActionPerformed(evt);
            }
        });

        btnBoleta.setFont(new java.awt.Font("Tahoma", 3, 15)); // NOI18N
        btnBoleta.setText("Boleta");
        btnBoleta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBoleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBoletaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtAño, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCiclo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCreditos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                        .addGap(108, 108, 108)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPlanEstudios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEscribir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCatalogoAsig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBoleta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEscribir)
                    .addComponent(txtCiclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPlanEstudios)
                    .addComponent(txtCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(btnCatalogoAsig)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBoleta)
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    static capanegocio.PlanEstudio planestudio = new capanegocio.PlanEstudio();
    private void btnEscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscribirActionPerformed
        
        
        String ciclo = txtCiclo.getText();
        String creditos = txtCreditos.getText();
        String año = txtAño.getText();

        //declarar un objeto plan de estudio
        planestudio.setCiclo(ciclo);
        planestudio.setCreditos(creditos);
        planestudio.setAño(año);

        //enviar mensaje de confirmación
        JOptionPane.showMessageDialog(null,"Datos almacenados correctamente");
    }//GEN-LAST:event_btnEscribirActionPerformed

    private void btnPlanEstudiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlanEstudiosActionPerformed
         JOptionPane.showMessageDialog(null,"Datos Plan de Estudio\n"+"\nCiclo: "+planestudio.getCiclo()
                                       +"\nCréditos: "+planestudio.getCreditos()+"\nAño: "+planestudio.getAño());
    }//GEN-LAST:event_btnPlanEstudiosActionPerformed

    private void btnCatalogoAsigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatalogoAsigActionPerformed
        JOptionPane.showMessageDialog(null,"En Mantenimiento\n");
    }//GEN-LAST:event_btnCatalogoAsigActionPerformed

    private void btnBoletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBoletaActionPerformed
        capapresentacion.frmMatricula frm = new capapresentacion.frmMatricula();
        //Mostrar el formulario
        frm.show();
    }//GEN-LAST:event_btnBoletaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPlanEstudio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPlanEstudio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPlanEstudio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPlanEstudio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPlanEstudio().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBoleta;
    private javax.swing.JButton btnCatalogoAsig;
    private javax.swing.JButton btnEscribir;
    private javax.swing.JButton btnPlanEstudios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtAño;
    private javax.swing.JTextField txtCiclo;
    private javax.swing.JTextField txtCreditos;
    // End of variables declaration//GEN-END:variables
}
